name: altaher_jewellery
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  dartz: ^0.10.1
  fluttertoast: ^8.2.2
  flutter_screenutil: ^5.8.4
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  curved_navigation_bar: ^1.0.3
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.0
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  freezed: ^2.4.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/fonts/Tajawal/
    - assets/fonts/Cairo/

  fonts:
    - family: BalooBhaijaan2
      fonts:
        - asset: assets/fonts/Baloo_Bhaijaan_2/BalooBhaijaan2-Regular.ttf
        - asset: assets/fonts/Baloo_Bhaijaan_2/BalooBhaijaan2-SemiBold.ttf
        - asset: assets/fonts/Baloo_Bhaijaan_2/BalooBhaijaan2-Bold.ttf
        - asset: assets/fonts/Baloo_Bhaijaan_2/BalooBhaijaan2-ExtraBold.ttf
        - asset: assets/fonts/Baloo_Bhaijaan_2/BalooBhaijaan2-Medium.ttf

    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai/Almarai-Light.ttf

